spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  data:
    r2dbc:
      generate-ddl: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  cache:
    type: caffeine