spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  data:
    r2dbc:
      generate-ddl: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always  # Siempre inicializa el esquema al arrancar
logging:
  level:
    org.springframework.boot.sql.init: DEBUG
    org.springframework.r2dbc.core: DEBUG